ors_api_key: "5b3ce3597851110001cf6248c8e57a115b0dc3314d3cdedbc38516f97ac457a2c3bdac9542cd1ec7"
default_columns:
  address: "DIRECCION"
  latitude: "LATITUD"
  longitude: "LONGITUD"
default_settings:
  service_time: 10
  start_time: "08:00"
  vehicles: 3
  balance: true
  balance_threshold: 0.9
  fuel_type: "diesel"
  fuel_price: 1.376
  fuel_consumption: 5.0
  price_per_hour: 14.0